<?php

use assets\services\WishService;
use core\manager\SessionManager;
use core\manager\UserManager;
use core\rest\UserRest;

/**
 * Created by PhpStorm.
 * User: 94201
 * Date: 11/21/2018
 * Time: 5:25 PM
 */
class AuthRest extends UserRest{

    public function POST_login(){
        parent::POST_login(); // TODO: Change the autogenerated stub
        $this->out->data->user = $this->userObject();
    }
    
    public function GET_check(){
        $this->out->data->user = $this->userObject();
    }

    private function userObject(){
        $res = new stdClass();
        $uid = UserManager::currentId();
        $sid = SessionManager::id();
        $res->updated = time();
        if($uid){
            $res->current = UserManager::current();
            if($uid == 3 || $uid == 4){
                $res->current->a = 1;
            }
            $res->wishes = WishService::getInstance()->usersList($uid);
        }else{
            $res->wishes = WishService::getInstance()->sessionsList($sid);
        }
        return $res;
    }

    public function postLoginUser(){
        parent::postLoginUser();
        $uid = UserManager::currentId();
        $sid = SessionManager::id();
        WishService::getInstance()->mergeSidToUser($sid, $uid);
    }

}